[package]
name = "x404"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
bonding_curve_launchpad = "0xa23f164e45f20fae76140e35c5908083562e214f11c0d0471ab12ed5b96d08f6"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies]
swap = { local = "../swap" }
aptos_404 = { local = "../aptos_404" }