[package]
name = "x404"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
bonding_curve_launchpad = "0x63bb743349bc759dd0c4bb0ff0b29b06ad222be053e7912acf5ede5a97b7104c"
deployer = "6b5dd370b613d3aa9761aefd65d590136d87cc3d0369b0f14f9cabc83d5b9fb1"
swap = "0x382a7483d472e344ab00a4c62a7db58d878e860fdb31b639806ff4871178ab62"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies]
swap = { local = "../swap" }
aptos_404 = { local = "../aptos_404" }