[package]
name = "x404"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
bonding_curve_launchpad = "0xd728a23cc674c12381a1908bf06efe42d87171958baed26d7b98a8b11af36eaf"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies]
swap = { local = "../swap" }
aptos_404 = { local = "../aptos_404" }