[package]
name = "swap"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
deployer = "9a8d32d60b04fecba61f999127e863d20e2dc832e78d0fcb2a86ae825db3fa2c"
swap = "0x2e29e4539d1d735e34ab7e2c59e3b38a18265a99fd3a58a9c4b434e7e9161739"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
aptos_404 = { local = "../aptos_404" }