[package]
name = "aptos_404"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
aptos_404 = "0xa1ca98a0ada029504cf0d59310050c545d115f589818d5addc6a66c60aa7c1f"

[dev-addresses]
aptos_404 = "0xa1ca98a0ada029504cf0d59310050c545d115f589818d5addc6a66c60aa7c1f"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"